# Generated by Django 5.1 on 2024-08-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_common', '0005_alter_user_options_user_name_user_prime_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='이 사용자가 활성화되어 있는지를 나타냅니다. 계정을 삭제하는 대신 이 옵션을 해제하세요.', verbose_name='활성'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='관리사이트 로그인 가능 여부를 나타냅니다.', verbose_name='스탭'),
        ),
    ]
