# Generated by Django 5.2 on 2025-09-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_common', '0006_remove_user_image_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='serial',
            field=models.CharField(default='', help_text='핸드폰 번호에서 010을 제외한 나머지 8자리를 입력해주세요', max_length=8, verbose_name='응시번호'),
        ),
    ]
