# Generated by Django 5.1 on 2024-08-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': '댓글', 'verbose_name_plural': '댓글'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': '공지사항', 'verbose_name_plural': '공지사항'},
        ),
    ]
