# Generated by Django 5.1 on 2024-08-30 02:44

import a_daily.models
import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('semester', models.IntegerField(choices=a_daily.models.semester_choice, default=a_daily.models.semester_default, verbose_name='기수')),
                ('circle', models.IntegerField(choices=a_daily.models.circle_choice, default=1, verbose_name='순환')),
                ('subject', models.CharField(choices=a_daily.models.subject_choice, default='형사', max_length=2, verbose_name='과목')),
                ('round', models.IntegerField(choices=a_daily.models.round_choice, default=1, verbose_name='회차')),
                ('number', models.IntegerField(default=1, verbose_name='번호')),
                ('count_1', models.IntegerField(default=0, verbose_name='①')),
                ('count_2', models.IntegerField(default=0, verbose_name='②')),
                ('count_3', models.IntegerField(default=0, verbose_name='③')),
                ('count_4', models.IntegerField(default=0, verbose_name='④')),
                ('count_0', models.IntegerField(default=0, verbose_name='미표기')),
                ('count_multiple', models.IntegerField(default=0, verbose_name='중복표기')),
                ('count_total', models.IntegerField(default=0, verbose_name='총계')),
                ('data', models.JSONField(default=dict, verbose_name='전체')),
            ],
            options={
                'verbose_name': '03_답안개수',
                'verbose_name_plural': '03_답안개수',
                'unique_together': {('semester', 'circle', 'subject', 'round', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=a_daily.models.semester_choice, default=a_daily.models.semester_default, verbose_name='기수')),
                ('circle', models.IntegerField(choices=a_daily.models.circle_choice, default=1, verbose_name='순환')),
                ('subject', models.CharField(choices=a_daily.models.subject_choice, default='형사', max_length=2, verbose_name='과목')),
                ('round', models.IntegerField(choices=a_daily.models.round_choice, default=1, verbose_name='회차')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='공개일시')),
                ('participants', models.IntegerField(default=0, verbose_name='응시생수')),
                ('statistics', models.JSONField(default=a_daily.models.statistics_default, verbose_name='성적 통계')),
            ],
            options={
                'verbose_name': '01_시험',
                'verbose_name_plural': '01_시험',
                'ordering': ['-semester', '-circle', 'subject', 'round'],
                'unique_together': {('semester', 'circle', 'subject', 'round')},
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=a_daily.models.semester_choice, default=75, verbose_name='기수')),
                ('circle', models.IntegerField(choices=a_daily.models.circle_choice, default=1, verbose_name='순환')),
                ('subject', models.CharField(choices=a_daily.models.subject_choice, default='형사', max_length=2, verbose_name='과목')),
                ('round', models.IntegerField(choices=a_daily.models.round_choice, default=1, verbose_name='회차')),
                ('number', models.IntegerField(choices=a_daily.models.number_choice, default=1, verbose_name='문제 번호')),
                ('answer', models.IntegerField(choices=a_daily.models.answer_choice, default=1, verbose_name='정답')),
                ('question', models.TextField(default='', verbose_name='발문')),
                ('data', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='문제 내용')),
                ('opened_at', models.DateField(default=django.utils.timezone.now, verbose_name='공개일')),
            ],
            options={
                'verbose_name': '02_문제',
                'verbose_name_plural': '02_문제',
                'ordering': ['-semester', 'id'],
                'unique_together': {('semester', 'circle', 'round', 'subject', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('semester', models.IntegerField(choices=a_daily.models.semester_choice, default=a_daily.models.semester_default, verbose_name='기수')),
                ('circle', models.IntegerField(choices=a_daily.models.circle_choice, default=1, verbose_name='순환')),
                ('subject', models.CharField(choices=a_daily.models.subject_choice, default='형사', max_length=2, verbose_name='과목')),
                ('round', models.IntegerField(choices=a_daily.models.round_choice, default=1, verbose_name='회차')),
                ('answer_student', models.JSONField(default=a_daily.models.answer_default, verbose_name='제출 답안')),
                ('answer_confirmed', models.BooleanField(default=False, verbose_name='답안 확정')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='점수')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='등수')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='주석')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '4_수험정보',
                'verbose_name_plural': '4_수험정보',
                'ordering': ['-semester', '-circle', 'subject', 'round'],
                'unique_together': {('user', 'semester', 'circle', 'subject', 'round')},
            },
        ),
    ]
