# Generated by Django 5.1 on 2024-08-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_weekly', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-semester', '-circle', 'subject', 'round'], 'verbose_name': '04_수험정보', 'verbose_name_plural': '04_수험정보'},
        ),
    ]
