# Generated by Django 5.1 on 2024-08-31 00:42

import a_common.model_settings
import ckeditor.fields
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_weekly', '0002_alter_student_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '07_태그',
                'verbose_name_plural': '07_태그',
                'db_table': 'a_weekly_problem_tag',
            },
        ),
        migrations.AlterModelOptions(
            name='answercount',
            options={'verbose_name': '13_답안개수', 'verbose_name_plural': '13_답안개수'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-semester', '-circle', 'subject', 'round'], 'verbose_name': '11_시험', 'verbose_name_plural': '11_시험'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-semester', 'id'], 'verbose_name': '01_문제', 'verbose_name_plural': '01_문제'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-semester', '-circle', 'subject', 'round'], 'verbose_name': '12_수험정보', 'verbose_name_plural': '12_수험정보'},
        ),
        migrations.AlterModelTable(
            name='answercount',
            table='a_weekly_answer_count',
        ),
        migrations.CreateModel(
            name='ProblemCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '09_컬렉션',
                'verbose_name_plural': '09_컬렉션',
                'db_table': 'a_weekly_problem_collection',
                'ordering': ['user', 'order'],
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ProblemCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_items', to='a_weekly.problemcollection')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_problems', to='a_weekly.problem')),
            ],
            options={
                'verbose_name': '10_컬렉션 문제',
                'verbose_name_plural': '10_컬렉션 문제',
                'db_table': 'a_weekly_problem_collection_item',
                'ordering': ['collection__user', 'collection', 'order'],
                'unique_together': {('collection', 'problem')},
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='collections',
            field=models.ManyToManyField(related_name='collected_problems', through='a_weekly.ProblemCollectionItem', to='a_weekly.problemcollection'),
        ),
        migrations.CreateModel(
            name='ProblemLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='a_weekly.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '03_즐겨찾기',
                'verbose_name_plural': '03_즐겨찾기',
                'db_table': 'a_weekly_problem_like',
                'ordering': ['-id'],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='like_users',
            field=models.ManyToManyField(related_name='weekly_liked_problems', through='a_weekly.ProblemLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProblemMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='a_weekly.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_memos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '06_메모',
                'verbose_name_plural': '06_메모',
                'db_table': 'a_weekly_problem_memo',
                'ordering': ['-id'],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='memo_users',
            field=models.ManyToManyField(related_name='weekly_memoed_problems', through='a_weekly.ProblemMemo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProblemOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='a_weekly.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_opens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '02_확인기록',
                'verbose_name_plural': '02_확인기록',
                'db_table': 'a_weekly_problem_open',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='open_users',
            field=models.ManyToManyField(related_name='weekly_opened_problems', through='a_weekly.ProblemOpen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProblemRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=a_common.model_settings.rating_choice, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='a_weekly.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '04_난이도',
                'verbose_name_plural': '04_난이도',
                'db_table': 'a_weekly_problem_rate',
                'ordering': ['-id'],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='rate_users',
            field=models.ManyToManyField(related_name='weekly_rated_problems', through='a_weekly.ProblemRate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProblemSolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=a_common.model_settings.answer_choice, default=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='a_weekly.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_solves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '05_정답확인',
                'verbose_name_plural': '05_정답확인',
                'db_table': 'a_weekly_problem_solve',
                'ordering': ['-id'],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='solve_users',
            field=models.ManyToManyField(related_name='weekly_solved_problems', through='a_weekly.ProblemSolve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProblemTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_problems', to='a_weekly.problem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='a_weekly.problemtag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tagged_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '08_태그 문제',
                'verbose_name_plural': '08_태그 문제',
                'db_table': 'a_weekly_problem_tagged_item',
                'unique_together': {('tag', 'content_object', 'user')},
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='a_weekly.ProblemTaggedItem', to='a_weekly.ProblemTag', verbose_name='Tags'),
        ),
    ]
