# Generated by Django 5.1 on 2024-10-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_weekly', '0003_alter_problem_opened_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='점수'),
        ),
    ]
