# Generated by Django 5.1 on 2024-08-20 09:30

import a_daily.models
import ckeditor.fields
import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=a_daily.models.semester_choice, default=75, verbose_name='기수')),
                ('circle', models.IntegerField(choices=a_daily.models.circle_choice, default=1, verbose_name='순환')),
                ('subject', models.CharField(choices=a_daily.models.subject_choice, default='형사', max_length=2, verbose_name='과목')),
                ('round', models.IntegerField(choices=a_daily.models.round_choice, default=1, verbose_name='회차')),
                ('number', models.IntegerField(choices=a_daily.models.number_choice, default=1, verbose_name='문제 번호')),
                ('answer', models.IntegerField(choices=a_daily.models.answer_choice, default=1, verbose_name='정답')),
                ('question', models.TextField(default='', verbose_name='발문')),
                ('data', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='문제 내용')),
                ('opened_at', models.DateField(default=django.utils.timezone.now, verbose_name='공개일')),
            ],
            options={
                'verbose_name': '01_문제',
                'verbose_name_plural': '01_문제',
                'ordering': ['-semester', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '07_태그',
                'verbose_name_plural': '07_태그',
                'db_table': 'a_daily_problem_tag',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=a_daily.models.semester_choice, default=a_daily.models.semester_default, verbose_name='기수')),
                ('circle', models.IntegerField(choices=a_daily.models.circle_choice, default=1, verbose_name='순환')),
                ('subject', models.CharField(choices=a_daily.models.subject_choice, default='형사', max_length=2, verbose_name='과목')),
                ('round', models.IntegerField(choices=a_daily.models.round_choice, default=1, verbose_name='회차')),
                ('opened_at', models.DateField(default=django.utils.timezone.now, verbose_name='공개일')),
                ('answer_official', models.JSONField(default=list, verbose_name='정답')),
                ('participants', models.IntegerField(default=0, verbose_name='응시생수')),
                ('statistics', models.JSONField(default=dict, verbose_name='성적 통계')),
            ],
            options={
                'verbose_name': '00_시험',
                'verbose_name_plural': '00_시험',
                'ordering': ['-semester', '-circle', 'subject', 'round'],
                'unique_together': {('semester', 'circle', 'subject', 'round')},
            },
        ),
        migrations.CreateModel(
            name='ProblemCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '09_컬렉션',
                'verbose_name_plural': '09_컬렉션',
                'db_table': 'a_daily_problem_collection',
                'ordering': ['user', 'order'],
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ProblemCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_items', to='a_daily.problemcollection')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_problems', to='a_daily.problem')),
            ],
            options={
                'verbose_name': '10_컬렉션 문제',
                'verbose_name_plural': '10_컬렉션 문제',
                'db_table': 'a_daily_problem_collection_item',
                'ordering': ['collection__user', 'collection', 'order'],
                'unique_together': {('collection', 'problem')},
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='collections',
            field=models.ManyToManyField(related_name='collected_problems', through='a_daily.ProblemCollectionItem', to='a_daily.problemcollection'),
        ),
        migrations.CreateModel(
            name='ProblemLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='a_daily.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '03_즐겨찾기',
                'verbose_name_plural': '03_즐겨찾기',
                'db_table': 'a_daily_problem_like',
                'ordering': ['-id'],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='like_users',
            field=models.ManyToManyField(related_name='daily_liked_problems', through='a_daily.ProblemLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProblemMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='a_daily.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_memos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '06_메모',
                'verbose_name_plural': '06_메모',
                'db_table': 'a_daily_problem_memo',
                'ordering': ['-id'],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='memo_users',
            field=models.ManyToManyField(related_name='daily_memoed_problems', through='a_daily.ProblemMemo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProblemOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='a_daily.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_opens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '02_확인기록',
                'verbose_name_plural': '02_확인기록',
                'db_table': 'a_daily_problem_open',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='open_users',
            field=models.ManyToManyField(related_name='daily_opened_problems', through='a_daily.ProblemOpen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProblemRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=a_daily.models.rating_choice, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='a_daily.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '04_난이도',
                'verbose_name_plural': '04_난이도',
                'db_table': 'a_daily_problem_rate',
                'ordering': ['-id'],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='rate_users',
            field=models.ManyToManyField(related_name='daily_rated_problems', through='a_daily.ProblemRate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProblemSolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=a_daily.models.answer_choice, default=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='a_daily.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_solves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '05_정답확인',
                'verbose_name_plural': '05_정답확인',
                'db_table': 'a_daily_problem_solve',
                'ordering': ['-id'],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='solve_users',
            field=models.ManyToManyField(related_name='daily_solved_problems', through='a_daily.ProblemSolve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProblemTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_problems', to='a_daily.problem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='a_daily.problemtag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tagged_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '08_태그 문제',
                'verbose_name_plural': '08_태그 문제',
                'db_table': 'a_daily_problem_tagged_item',
                'unique_together': {('tag', 'content_object', 'user')},
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='a_daily.ProblemTaggedItem', to='a_daily.ProblemTag', verbose_name='Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('semester', 'circle', 'round', 'subject', 'number')},
        ),
    ]
