# Generated by Django 5.1 on 2024-08-18 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_daily', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='opened_at',
            field=models.DateField(default=datetime.date.today, verbose_name='공개일'),
        ),
    ]
