# Generated by Django 5.1 on 2024-08-24 10:25

import a_daily.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_daily', '0002_alter_exam_options_alter_exam_answer_official_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answercount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='answercount',
            name='circle',
            field=models.IntegerField(choices=a_daily.models.circle_choice, default=1, verbose_name='순환'),
        ),
        migrations.AddField(
            model_name='answercount',
            name='round',
            field=models.IntegerField(choices=a_daily.models.round_choice, default=1, verbose_name='회차'),
        ),
        migrations.AddField(
            model_name='answercount',
            name='semester',
            field=models.IntegerField(choices=a_daily.models.semester_choice, default=a_daily.models.semester_default, verbose_name='기수'),
        ),
        migrations.AddField(
            model_name='answercount',
            name='subject',
            field=models.CharField(choices=a_daily.models.subject_choice, default='형사', max_length=2, verbose_name='과목'),
        ),
        migrations.RemoveField(
            model_name='answercount',
            name='exam',
        ),
    ]
