# Generated by Django 5.1 on 2024-08-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_daily', '0003_alter_answercount_unique_together_answercount_circle_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answercount',
            unique_together={('semester', 'circle', 'subject', 'round', 'number')},
        ),
    ]
