# Generated by Django 5.1 on 2024-08-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_daily', '0004_alter_answercount_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='등수'),
        ),
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='점수'),
        ),
    ]
