# Generated by Django 5.2 on 2025-09-23 01:29

import a_common.prime_test.model_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_daily', '0004_alter_student_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='semester',
            field=models.IntegerField(choices=a_common.prime_test.model_settings.semester_choice, default=a_common.prime_test.model_settings.semester_default, verbose_name='기수'),
        ),
    ]
