# Generated by Django 5.1 on 2024-08-29 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_daily', '0005_alter_student_rank_alter_student_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='answer_official',
        ),
        migrations.AlterField(
            model_name='exam',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='공개일시'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
    ]
