# Generated by Django 5.1 on 2024-08-31 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_daily', '0006_remove_exam_answer_official_alter_exam_opened_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answercount',
            table='a_daily_answer_count',
        ),
    ]
