# Generated by Django 5.1 on 2024-08-31 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_daily', '0007_alter_answercount_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='exam',
            table='a_daily_exam',
        ),
        migrations.AlterModelTable(
            name='problem',
            table='a_daily_problem',
        ),
        migrations.AlterModelTable(
            name='student',
            table='a_daily_student',
        ),
    ]
