# Generated by Django 5.1 on 2024-08-31 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_daily', '0008_alter_student_user_alter_exam_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answercount',
            options={'ordering': ['-semester', '-circle', 'subject', 'round', 'number'], 'verbose_name': '13_답안개수', 'verbose_name_plural': '13_답안개수'},
        ),
    ]
