# Generated by Django 5.0.6 on 2024-06-30 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_official', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemcollect',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='problemcollecteditem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='problemcomment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='problemlike',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='problemmemo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='problemopen',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='problemrate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='problemsolve',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='remarks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemcollect',
            name='remarks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemcollecteditem',
            name='remarks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemcomment',
            name='remarks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemlike',
            name='remarks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemmemo',
            name='remarks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemopen',
            name='remarks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemrate',
            name='remarks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemsolve',
            name='remarks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
