# Generated by Django 5.1 on 2024-08-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_official', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='comment_users',
        ),
        migrations.RemoveField(
            model_name='problemcommentlike',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='problemcommentlike',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-year', 'id'], 'verbose_name': '01_문제', 'verbose_name_plural': '01_문제'},
        ),
        migrations.AlterModelOptions(
            name='problemcollection',
            options={'ordering': ['user', 'order'], 'verbose_name': '09_컬렉션', 'verbose_name_plural': '09_컬렉션'},
        ),
        migrations.AlterModelOptions(
            name='problemcollectionitem',
            options={'ordering': ['collection__user', 'collection', 'order'], 'verbose_name': '10_컬렉션 문제', 'verbose_name_plural': '10_컬렉션 문제'},
        ),
        migrations.AlterModelOptions(
            name='problemlike',
            options={'ordering': ['-id'], 'verbose_name': '03_즐겨찾기', 'verbose_name_plural': '03_즐겨찾기'},
        ),
        migrations.AlterModelOptions(
            name='problemmemo',
            options={'ordering': ['-id'], 'verbose_name': '06_메모', 'verbose_name_plural': '06_메모'},
        ),
        migrations.AlterModelOptions(
            name='problemopen',
            options={'verbose_name': '02_확인기록', 'verbose_name_plural': '02_확인기록'},
        ),
        migrations.AlterModelOptions(
            name='problemrate',
            options={'ordering': ['-id'], 'verbose_name': '04_난이도', 'verbose_name_plural': '04_난이도'},
        ),
        migrations.AlterModelOptions(
            name='problemsolve',
            options={'ordering': ['-id'], 'verbose_name': '05_정답확인', 'verbose_name_plural': '05_정답확인'},
        ),
        migrations.AlterModelOptions(
            name='problemtag',
            options={'verbose_name': '07_태그', 'verbose_name_plural': '07_태그'},
        ),
        migrations.AlterModelOptions(
            name='problemtaggeditem',
            options={'verbose_name': '08_태그 문제', 'verbose_name_plural': '08_태그 문제'},
        ),
        migrations.DeleteModel(
            name='ProblemComment',
        ),
        migrations.DeleteModel(
            name='ProblemCommentLike',
        ),
    ]
