# Generated by Django 5.1 on 2025-04-10 07:03

import a_official.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_official', '0002_remove_problem_comment_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='year',
            field=models.IntegerField(choices=a_official.models.year_choice, default=a_official.models.default_year, verbose_name='연도'),
        ),
    ]
