# Generated by Django 5.0.6 on 2024-06-30 09:06

import a_official.models.base_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_official', '0002_remove_problemcollect_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.IntegerField(choices=a_official.models.base_settings.answer_choices, default=1),
        ),
    ]
