# Generated by Django 5.0.6 on 2024-07-01 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_official', '0004_alter_department_remarks_alter_exam_remarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemtaggeditem',
            old_name='active',
            new_name='is_tagged',
        ),
    ]
