# Generated by Django 5.2 on 2025-07-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_official', '0004_exam_predictanswercount_predictanswercountlowrank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='exam',
            new_name='exam_name',
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('year', 'exam_name', 'subject', 'number')},
        ),
    ]
