# Generated by Django 5.2 on 2025-07-08 06:20

import a_official.models.official_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_official', '0005_rename_exam_problem_exam_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='a_official.exam', verbose_name='시험'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='exam_name',
            field=models.CharField(choices=a_official.models.choices.exam_choice, default='경위', max_length=2, verbose_name='시험 이름'),
        ),
    ]
