# Generated by Django 5.0.6 on 2024-07-01 02:53

import a_official.models.base_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_official', '0005_rename_active_problemtaggeditem_is_tagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsolve',
            name='answer',
            field=models.IntegerField(choices=a_official.models.base_settings.answer_choices),
        ),
    ]
