# Generated by Django 5.2 on 2025-07-08 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_official', '0006_problem_exam_alter_problem_exam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='a_official.exam', verbose_name='시험'),
        ),
    ]
