# Generated by Django 5.0.6 on 2024-07-01 03:04

import a_official.models.base_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_official', '0006_alter_problemsolve_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemrate',
            name='rating',
            field=models.IntegerField(choices=a_official.models.base_settings.rating_choices),
        ),
    ]
