# Generated by Django 5.2 on 2025-07-08 07:02

import a_official.models.official_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_official', '0007_alter_problem_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam',
            field=models.CharField(choices=a_official.models.choices.exam_choice, default='경위', max_length=2, verbose_name='시험'),
        ),
    ]
