# Generated by Django 5.0.6 on 2024-07-02 13:50

import a_official.models.base_settings
import ckeditor.fields
import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_official', '0007_alter_problemrate_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['order'], 'verbose_name': '직렬', 'verbose_name_plural': '직렬'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': '시험', 'verbose_name_plural': '시험'},
        ),
        migrations.AlterModelOptions(
            name='problemcollecteditem',
            options={'verbose_name': '기출문제 컬렉션 문제', 'verbose_name_plural': '기출문제 컬렉션 문제'},
        ),
        migrations.AlterModelOptions(
            name='problemtaggeditem',
            options={'verbose_name': '기출문제 태그 문제', 'verbose_name_plural': '기출문제 태그 문제'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['order'], 'verbose_name': '모집단위', 'verbose_name_plural': '모집단위'},
        ),
        migrations.RemoveField(
            model_name='problemcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='problemmemo',
            name='memo',
        ),
        migrations.AddField(
            model_name='problemcomment',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='problemmemo',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='department',
            name='exam',
            field=models.CharField(choices=a_official.models.base_settings.exam_choices, default='경위', max_length=2, verbose_name='시험'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=a_official.models.base_settings.department_choices, default='일반', max_length=10, verbose_name='직렬'),
        ),
        migrations.AlterField(
            model_name='department',
            name='order',
            field=models.IntegerField(verbose_name='순서'),
        ),
        migrations.AlterField(
            model_name='department',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='주석'),
        ),
        migrations.AlterField(
            model_name='department',
            name='unit',
            field=models.CharField(choices=a_official.models.base_settings.unit_choices, default='경위', max_length=10, verbose_name='모집단위'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='answer_official',
            field=models.JSONField(default=dict, verbose_name='공식 정답'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='answer_official_opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='공식 정답 공개 일시'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='answer_predict_opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='예상 정답 공개 일시'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam',
            field=models.CharField(choices=a_official.models.base_settings.exam_choices, default='경위', max_length=2, verbose_name='시험'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_finished_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='시험 종료 일시'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='시험 시작 일시'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='page_opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='페이지 공개 일시'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='주석'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='round',
            field=models.IntegerField(default=0, verbose_name='회차'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.IntegerField(choices=a_official.models.base_settings.year_choices, default=2024, verbose_name='연도'),
        ),
        migrations.AlterField(
            model_name='predictanswercount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='predictanswerrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='predictanswerrecord',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='주석'),
        ),
        migrations.AlterField(
            model_name='predictstudent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='predictstudent',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='주석'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.IntegerField(choices=a_official.models.base_settings.answer_choices, default=1, verbose_name='정답'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='data',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='문제 내용'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='exam',
            field=models.CharField(choices=a_official.models.base_settings.exam_choices, default='경위', max_length=10, verbose_name='시험'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='number',
            field=models.IntegerField(choices=a_official.models.base_settings.number_choices, default=1, verbose_name='문제 번호'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='question',
            field=models.TextField(verbose_name='발문'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='주석'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='subject',
            field=models.CharField(choices=a_official.models.base_settings.subject_choices, default='형사', max_length=10, verbose_name='과목'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='year',
            field=models.IntegerField(choices=a_official.models.base_settings.year_choices, default=2025, verbose_name='연도'),
        ),
        migrations.AlterField(
            model_name='problemcollect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='problemcollect',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='problemcollect',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='주석'),
        ),
        migrations.AlterField(
            model_name='problemcollect',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='problemcollecteditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='problemcollecteditem',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='problemcollecteditem',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='주석'),
        ),
        migrations.AlterField(
            model_name='problemcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='problemcomment',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='주석'),
        ),
        migrations.AlterField(
            model_name='problemcomment',
            name='title',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='problemlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='problemlike',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='주석'),
        ),
        migrations.AlterField(
            model_name='problemmemo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='problemmemo',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='주석'),
        ),
        migrations.AlterField(
            model_name='problemopen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='problemopen',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='주석'),
        ),
        migrations.AlterField(
            model_name='problemrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='problemrate',
            name='rating',
            field=models.IntegerField(choices=a_official.models.base_settings.rating_choices, default=1),
        ),
        migrations.AlterField(
            model_name='problemrate',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='주석'),
        ),
        migrations.AlterField(
            model_name='problemsolve',
            name='answer',
            field=models.IntegerField(choices=a_official.models.base_settings.answer_choices, default=1),
        ),
        migrations.AlterField(
            model_name='problemsolve',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='problemsolve',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problemsolve',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='주석'),
        ),
        migrations.AlterField(
            model_name='problemtaggeditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='problemtaggeditem',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='주석'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='exam',
            field=models.CharField(choices=a_official.models.base_settings.exam_choices, default='경위', max_length=2, verbose_name='시험'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(choices=a_official.models.base_settings.unit_choices, default='경위', max_length=10, verbose_name='모집단위'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='order',
            field=models.IntegerField(verbose_name='순서'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='주석'),
        ),
    ]
