# Generated by Django 5.2 on 2025-07-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_official', '0008_alter_exam_exam'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='predictexam',
            table='a_official_predict_exam',
        ),
    ]
