# Generated by Django 5.2 on 2025-07-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_official', '0009_alter_predictexam_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictstudent',
            name='password',
            field=models.CharField(default=1234, max_length=10, verbose_name='비밀번호'),
            preserve_default=False,
        ),
    ]
