# Generated by Django 5.2 on 2025-07-17 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_official', '0010_alter_predictstudent_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictstudent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="전화번호는 '010-1234-5678' 형식으로 저장됩니다.", regex='^010-\\d{4}-\\d{4}$')], verbose_name='휴대폰 번호'),
        ),
    ]
