# Generated by Django 5.2 on 2025-09-23 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_official', '0011_predictstudent_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictstudent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="'010-1234-5678' 형식으로 입력해주세요.", regex='^010-\\d{4}-\\d{4}$')], verbose_name='휴대폰 번호'),
        ),
    ]
